name: build
on:
  schedule:
  - cron: '0 5 * * *'
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test
    - name: clippy
      run: cargo clippy --tests --examples
    - name: doc
      run: cargo doc
    - name: fmt
      run: cargo fmt --check
  libm:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test --features libm
    - name: clippy
      run: cargo clippy --tests --examples --features libm
    - name: doc
      run: cargo doc --features libm
  target-features:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test --features target-features
    - name: clippy
      run: cargo clippy --tests --examples --features target-features
    - name: doc
      run: cargo doc --features target-features
